### PR TITLE
fix: Upgrade cert-manager to 1.2.0

### PR DESCRIPTION
**Pull request by babadofar**
Upgrade notes https://cert-manager.io/docs/installation/upgrading/upgrading-1.1-1.2/

### CODE REVIEW

**Comment by ankitm123** [comment]
Probably better to upgrade to https://github.com/jetstack/cert-manager/releases/tag/v1.6.1, as it has a fix for the backward compatible change in 1.6.0?

**Comment by ankitm123** [comment]
In the meantime 1.7.0 is out, and 1.6.1 has a new bug, which is addressed in 1.6.2 :grimacing:

**Comment by babadofar** [comment]
Ok, we should test out version 1.7.0

**Comment by rawlingsj** [comment]
One thing the BDD tests wont do is test an upgrade of an existing cert-manager enabled cluster.  Once this PR merges teams will upgrade and if there's issues could break their installs so it is probably worth confirming a manual upgrade works too.

**Comment by ankitm123** [comment]
Btw AWS ACM needs atleast 1.4+ version of cert manager: https://github.com/cert-manager/aws-privateca-issuer#supported-workflows

**Comment by babadofar** [comment]
I have this working on three clusters. I had to update an issuer we had created in our cluster to the latest api version. But the clusterissuer in the jx namespace is already on apiversion/v1 so this should be OK.

May need to create a "breaking change" version, for those who already have issuers on the old version

**Comment by m1pl** [comment]
I upgraded one staging cluster to cert-manager 1.7.1 and everything works as expected, nothing broken.

**Comment by babadofar** [comment]
I just upgraded to 1.7.1 as well, and saw no problems. If somebody created their own CRD, for instance Issuer or ClusterIssuer, they may be need to manually upgrade these. 
https://cert-manager.io/docs/installation/upgrading/ingress-class-compatibility/ 
How can we proceed to have this PR merged?

**Comment by ankitm123** [comment]
@babadofar can we do upgrade of one minor version - it is fine by me, if it involves multiple PRs, but the recommendation from cert manager is to update one minor version at a time. Source: https://cert-manager.io/docs/installation/upgrading/

**Pull request merged**
