### PR TITLE
feat: upgrade tekton pipelines

### PR DESCRIPTION
**Pull request by tomhobson**

### CODE REVIEW

**Comment by msvticket** [comment]
Is there a reason for removing affinities like 

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: NotIn
                    values:
                      - windows
```

that are present in the manifest from the tekton project?

**Comment by tomhobson** [comment]
> Is there a reason for removing affinities like
> 
> ```
>       affinity:
>         nodeAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>             nodeSelectorTerms:
>               - matchExpressions:
>                   - key: kubernetes.io/os
>                     operator: NotIn
>                     values:
>                       - windows
> ```
> 
> that are present in the manifest from the tekton project?

hey @msvticket, welcome back. i think this is a side effect of the tekton helm chart being updated to allow for overrides of the node affinities. it shouldn't cause a problem as jenkins-x is unsupported on windows

**Comment by tomhobson** [comment]
@msvticket resolved within the chart, I've bumped the version still, but the templating won't change as we're overriding the node affinity

**Comment by msvticket** [comment]
> @msvticket resolved within the chart, I've bumped the version still, but the templating won't change as we're overriding the node affinity

That's how you have implemented it now, yes. You could copy the nodeAffinity from the manifest to the values.yaml. That is how it is done for gitResolverConfig, configDefaults and featureFlags. I think you should do it in that way.

**Comment by tomhobson** [comment]
this can be closed now as it's been resolved and upgraded

**Pull request closed without merging**
