### PR TITLE
fix: manually bump catalog version to upgrade to updatebot 0.3.6

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Review by babadofar — APPROVED** [review]

**Comment by ankitm123** [comment]
/retest
Seeing this error a lot:
```
Invalid pipeline status: pending
```

**Comment by ankitm123** [comment]
I will investigate the test issues in another pr.

**Pull request merged**
