### PR TITLE
fix: auto update nginx helm chart

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Comment by msvticket** [comment]
I'm actually sceptical to this fix. Shouldn't the version rather follow the version stream? 

To recollect: The reason for installing nginx with terraform is so the loadbalancer service is deleted before the cluster is destroyed so that the ELB is removed. But I would prefer to go back to installing the ingress controller with helmfile and
instead delete the services explicitly on destroy of the cluster.

That will also IMO make it easier to configure nginx.

**Comment by ankitm123** [comment]
>The reason for installing nginx with terraform is so the loadbalancer service is deleted before the cluster is destroyed so that the ELB is removed. 

It is only true in case of AWS, and even that is not the default option.

> But I would prefer to go back to installing the ingress controller with helmfile and
instead delete the services explicitly on destroy of the cluster.

This is still the default option atm.

All this PR does is automatically upgrade the nginx charts when there is a new version available upstream. 
Atm, we do it manually, and as we have seen in the past, we get stuck on old versions all the time.

**Review by msvticket — APPROVED** [review]

**Comment by ankitm123** [comment]
failed because of unrelated issue: 
```
no need to gh auth as using github.com
--
  |   |   |   | Flag --confirm has been deprecated, Pass any argument to skip confirmation prompt
  |   |   |   | GraphQL: Could not clone: Name already exists on this account (cloneTemplateRepository)
```

Will investigate this issue soon, for now, good to merge.

**Comment by ankitm123** [comment]
Actually this issue happens because of 2 reasons:
* We dont delete repos after testing :facepalm:
* When we create a pa, we only take into account existing pa's in the cluster, not the ones stored in LTS.

In this case, all pas for this PR are gc'ed from the cluster, so it creates a pa with build number 1. But a repo exists with the same name, and so it fails.

**Pull request merged**
