### PR TITLE
chore: change oauth2-proxy from k8s-at-home to the official chart

### PR DESCRIPTION
**Pull request by pokerface3**

### CODE REVIEW

**Comment by haysclark** [comment]
It might be a smoother transition to first bump the existing [k8s-at-home/oauth2-proxy](https://artifacthub.io/packages/helm/k8s-at-home/oauth2-proxy) to v5.0.7 as this version used the latest `oauth2-proxy` version: v7.1.3

Then switch over to the official chart?

**Comment by pokerface3** [comment]
I switched locally to the official chart and it works. Plus, I'm of the vain we should use official since it is likely to have the most support and eyes on it. Also, I tried v5.0.7. It didn't work because for some reason it was still trying to use network/v1beta1 which the nginx in the cluster didn't like.

**Comment by haysclark** [comment]
@pokerface3 Your totally right! My bad.

The latest v5.0.7 version of `k8s-at-home/oauth2-proxy` uses the outdated syntax in its Template: [k8s-at-home/oauth2-proxy template](
https://artifacthub.io/packages/helm/k8s-at-home/oauth2-proxy?modal=template&template=configmap-authenticated-emails-file.yaml)

**Comment by haysclark** [comment]
@ankitm123 I can confirm that the setting in this PR will unblock 1.22 users and close Issue https://github.com/jenkins-x/jx/issues/8212

Confirmation steps:
> I already had the setup from the JX docs site: [OAuth: How to protect Pipeline Visualizer with OAuth](https://jenkins-x.io/v3/admin/setup/ingress/oauth/) 
> Thus, I removed *k8s-at-home* `repositories` and `releases` helmfile settings but kept `pv-values.yaml` file

1. Added the following snippets to `helmfiles/jx/helmfile.yaml` 

```
repositories:
- name: oauth2-proxy
  url: https://oauth2-proxy.github.io/manifests
```
AND
```
releases:
- chart: oauth2-proxy/oauth2-proxy
  version: 6.2.1
  name: oauth2-proxy
  values:
  - ./charts/oauth2-proxy/oauth2-proxy/values.yaml.gotmpl
  - jx-values.yaml
  - extraArgs:
      provider: google
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
```

3. Creates a `helmfiles/jx/charts/oauth2-proxy/oauth2-proxy/` folder with the `defaults.yaml`, `secret-schema.yaml`, and `values.yaml.gotmpl` from this PR.

4. Ran `helmfile --file helmfile.yaml template --validate --include-crds --output-dir-template /tmp/generate/{{.Release.Namespace}}/{{.Release.Name}}` to confirm generated Ingress config.

5. After committing change I confirmed *OAuth2* works for *Dashboard* and *Lighthouse Merge Status* pages. 🥳  

Great work @pokerface3!

**Comment by ankitm123** [comment]
I will review it this week. We are planning to migrate the jx internal GCP infra to use oauth instead of password based authentication for things like the dashboard. Once I complete the migration, I can upgrade and test this PR out :)

**Comment by ankitm123** [comment]
@pokerface3 can you rebase with the latest master? The release pipeline has been fixed partially.

**Comment by tomhobson** [comment]
Closing, if this pr isn't dead, feel free to comment and I'll reopen!

**Pull request closed without merging**
