### PR TITLE
fix: increase polling interval if we're using Azure Key Vault

### PR DESCRIPTION
**Pull request by hervelemeur**
The default polling of 1000ms is too short and triggers the rate limiting.

### CODE REVIEW

**Comment by rawlingsj** [comment]
We could probably make this the default for all, lemme update your PR if you don''t mind...

**Comment by hervelemeur** [comment]
/hold

> We could probably make this the default for all
Need to take in account the `env:` declared below too, updating my pr

**Comment by hervelemeur** [comment]
/hold cancel

The 2 first `if` concerning AWS could be regrouped as they only have their urls as difference, but not sure at the moment of the syntax of an `if eq or () ()`, I've let them as they were.

**Pull request merged**
