### PR TITLE
chore: upgrade tekton to 0.33.4

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Comment by ankitm123** [comment]
Important: after this is merged, we only support kubernetes 1.21+.

**Review by tomhobson — APPROVED** [review]
LGTM. I think that cloud providers are no longer supporting 1.20 anyway (at least MS isn't)

**Review by babadofar — APPROVED** [review]

**Pull request merged**
